---
#
# - hosts: postgres-reyhoon
#   become: true
#   remote_user: rhnadmin
#   tasks:
#     - name: install postgresql
#       register: result
#       import_role:
#         name: geerlingguy.postgresql
#       vars:
#         postgresql_hba_entries:
#           - { type: local, database: all, user: postgres, auth_method: peer }
#           - { type: local, database: all, user: all, auth_method: peer }
#           - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
#           - { type: host, database: all, user: all, address: '172.20.1.0/24', auth_method: md5 }
#           - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
#
#         postgresql_locales:
#           - 'en_US.UTF-8'


- hosts: postgres-integrations
  become: true
  become_user: postgres
  remote_user: rhnadmin
  tasks:
  - name: postgres user=rhnadmin
    postgresql_user:
      name: rhnadmin
      password: ism5zpfhRMGFGQwC
      role_attr_flags: LOGIN,CREATEDB,CREATEROLE,INHERIT,SUPERUSER,NOREPLICATION,NOBYPASSRLS
      expires: infinity

  - name: postgres db=adjust-integration
    postgresql_db:
      name: adjust-integration
      encoding: UTF-8
      lc_collate: en_US.UTF-8
      lc_ctype: en_US.UTF-8
      owner: rhnadmin

  - name: postgres db=defaultdb
    postgresql_db:
      name: defaultdb
      encoding: UTF-8
      lc_collate: en_US.UTF-8
      lc_ctype: en_US.UTF-8
      owner: rhnadmin

  - name: postgres db=alopeyk-integration
    postgresql_db:
      name: alopeyk-integration
      encoding: UTF-8
      lc_collate: en_US.UTF-8
      lc_ctype: en_US.UTF-8
      owner: rhnadmin

  - name: postgres user=metabse
    postgresql_user:
      name: superset
      db: alopeyk-integration
      password: CTi12TUsxiRp2Wg6
      role_attr_flags: LOGIN,INHERIT
      expires: infinity
