---

- hosts: all
  remote_user: rhnadmin
  become: yes
  tasks:
    - name: net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: 65535
        state: present

    - name: vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: net.ipv4.tcp_sack
      sysctl:
        name: net.ipv4.tcp_sack
        value: 1
        state: present

    - name: net.ipv4.tcp_timestamps
      sysctl:
        name: net.ipv4.tcp_timestamps
        value: 1
        state: present

    - name: net.ipv4.tcp_window_scaling
      sysctl:
        name: net.ipv4.tcp_window_scaling
        value: 1
        state: present

    - name: net.ipv4.tcp_congestion_control
      sysctl:
        name: net.ipv4.tcp_congestion_control
        value: cubic
        state: present

    - name: net.ipv4.tcp_tw_recycle
      sysctl:
        name: net.ipv4.tcp_tw_recycle
        value: 1
        state: present

    - name: net.ipv4.tcp_max_syn_backlog
      sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 65535
        state: present

    - name: vm.overcommit_memory
      sysctl:
        name: vm.overcommit_memory
        value: 1
        state: present
        reload: yes


- hosts: all
  remote_user: rhnadmin
  become: yes
  tasks:
    - name:  no file
      pam_limits:
        domain: ansible
        limit_type: soft
        limit_item: nofile
        value: 500000

    # - name:
    #     pam_limits:
    #       domain: ansible
    #       limit_type: soft
    #       limit_item: core
    #       value: 64000

    - name: message queue
      pam_limits:
        domain: ansible
        limit_type: soft
        limit_item: msgqueue
        value: 819200

    # - name:
    #     pam_limits:
    #       domain: ansible
    #       limit_type: soft
    #       limit_item: cpu
    #       value: 64000

    - name: stack files
      pam_limits:
        domain: ansible
        limit_type: soft
        limit_item: stack
        value: 8192

    # - name:
    #     pam_limits:
    #       domain: ansible
    #       limit_type: soft
    #       limit_item: filesize
    #       value: 64000

    - name: signal pending
      pam_limits:
        domain: ansible
        limit_type: soft
        limit_item: sigpending
        value: 15681

      # - name:
      #     pam_limits:
      #       domain: ansible
      #       limit_type: soft
      #       limit_item: priority
      #       value: 0

- hosts: infra
  remote_user: rhnadmin
  become: yes
  tasks:
    - name: vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 1
        state: present
        reload: yes


#   core file size          (blocks, -c) 0
# data seg size           (kbytes, -d) unlimited
# scheduling priority             (-e) 0
# file size               (blocks, -f) unlimited
# pending signals                 (-i) 15681
# max locked memory       (kbytes, -l) 64
# max memory size         (kbytes, -m) unlimited
# open files                      (-n) 500000
# pipe size            (512 bytes, -p) 8
# POSIX message queues     (bytes, -q) 819200
# real-time priority              (-r) 0
# stack size              (kbytes, -s) 8192
# cpu time               (seconds, -t) unlimited
# max user processes              (-u) 15681
# virtual memory          (kbytes, -v) unlimited
# file locks                      (-x) unlimited
#
#
#
# - hosts: backend
#   remote_user: rhnadmin
#   become: yes
#   tasks:
#     - name: net.ipv4.tcp_max_syn_backlog
#       sysctl:
#         name: net.ipv4.tcp_max_syn_backlog
#         value: 8192
#         state: present
