---
ntp_timezone: Asia/Tehran
http_proxy: http://fodev.org
socks_proxy: socks5://127.0.0.1:8080

docker_socks_proxy: 'ALL_PROXY=socks5://127.0.0.1:8080'
docker_http_proxy: 'HTTP_PROXY=http://fodev.org:8118'
docker_https_proxy: 'HTTP_PROXY=http://fodev.org:8118'

docker_no_proxy: 'NO_PROXY=localhost,127.0.0.1,172.20.1.8'

users:
  - "ansible"
